// Mock recipe data for demonstration
export const mockRecipes = [
  // Italian Recipes
  {
    id: "spaghetti-carbonara",
    title: "Classic Spaghetti Carbonara",
    description:
      "Creamy Roman pasta dish with eggs, cheese, pancetta, and black pepper. A timeless Italian comfort food.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 20,
    servings: 4,
    difficulty: "Medium" as const,
    rating: 4.8,
    category: "Italian",
    ingredients: [
      "400g spaghetti pasta",
      "200g pancetta or guanciale, diced",
      "4 large eggs",
      "100g Pecorino Romano cheese, grated",
      "50g Parmesan cheese, grated",
      "Freshly ground black pepper",
      "Salt to taste",
      "2 cloves garlic (optional)",
    ],
    instructions: [
      "Bring a large pot of salted water to boil and cook spaghetti according to package directions until al dente.",
      "While pasta cooks, heat a large skillet over medium heat and cook pancetta until crispy, about 5-7 minutes.",
      "In a bowl, whisk together eggs, grated cheeses, and a generous amount of black pepper.",
      "Reserve 1 cup of pasta cooking water, then drain the pasta.",
      "Immediately add hot pasta to the skillet with pancetta and toss to combine.",
      "Remove from heat and quickly stir in the egg mixture, adding pasta water gradually to create a creamy sauce.",
      "Serve immediately with extra cheese and black pepper on top.",
    ],
  },
  {
    id: "margherita-pizza",
    title: "Margherita Pizza",
    description: "Traditional Neapolitan pizza with fresh mozzarella, tomatoes, and basil. Simple yet perfect.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 45,
    servings: 2,
    difficulty: "Medium" as const,
    rating: 4.7,
    category: "Italian",
    ingredients: [
      "1 ball pizza dough (store-bought or homemade)",
      "1/2 cup pizza sauce or marinara",
      "8 oz fresh mozzarella, sliced",
      "2 large tomatoes, sliced",
      "Fresh basil leaves",
      "Extra virgin olive oil",
      "Salt and pepper to taste",
      "Semolina flour for dusting",
    ],
    instructions: [
      "Preheat oven to 500°F (260°C). If using a pizza stone, place it in the oven while preheating.",
      "Roll out pizza dough on a floured surface to desired thickness.",
      "Transfer dough to a pizza pan or parchment paper if using a pizza stone.",
      "Spread pizza sauce evenly over the dough, leaving a 1-inch border for the crust.",
      "Arrange mozzarella slices and tomato slices evenly over the sauce.",
      "Season with salt and pepper, then drizzle lightly with olive oil.",
      "Bake for 12-15 minutes until crust is golden and cheese is bubbly.",
      "Remove from oven and immediately top with fresh basil leaves before serving.",
    ],
  },
  {
    id: "chicken-parmigiana",
    title: "Chicken Parmigiana",
    description: "Breaded chicken breast topped with marinara sauce and melted mozzarella cheese.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 35,
    servings: 4,
    difficulty: "Medium" as const,
    rating: 4.6,
    category: "Italian",
    ingredients: [
      "4 boneless chicken breasts, pounded thin",
      "1 cup all-purpose flour",
      "2 eggs, beaten",
      "2 cups Italian breadcrumbs",
      "2 cups marinara sauce",
      "2 cups mozzarella cheese, shredded",
      "1/2 cup Parmesan cheese, grated",
      "Vegetable oil for frying",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "Season chicken breasts with salt and pepper.",
      "Set up breading station: flour in one dish, beaten eggs in another, breadcrumbs in a third.",
      "Dredge each chicken breast in flour, then egg, then breadcrumbs, pressing to adhere.",
      "Heat oil in a large skillet over medium-high heat and fry chicken until golden, about 3-4 minutes per side.",
      "Transfer chicken to a baking dish and top each piece with marinara sauce and cheeses.",
      "Bake for 15-20 minutes until chicken is cooked through and cheese is melted and bubbly.",
      "Let rest for 5 minutes before serving with pasta or salad.",
    ],
  },

  // Asian Recipes
  {
    id: "pad-thai",
    title: "Authentic Pad Thai",
    description: "Sweet and tangy Thai stir-fried noodles with shrimp, tofu, and fresh vegetables.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 25,
    servings: 3,
    difficulty: "Medium" as const,
    rating: 4.5,
    category: "Asian",
    ingredients: [
      "8 oz rice noodles (pad thai width)",
      "1 lb medium shrimp, peeled",
      "4 oz firm tofu, cubed",
      "3 eggs, lightly beaten",
      "1 cup bean sprouts",
      "4 green onions, chopped",
      "3 tbsp tamarind paste",
      "3 tbsp fish sauce",
      "2 tbsp brown sugar",
      "2 tbsp vegetable oil",
      "Crushed peanuts and lime wedges for serving",
    ],
    instructions: [
      "Soak rice noodles in warm water until soft and pliable, about 30 minutes.",
      "Mix tamarind paste, fish sauce, and brown sugar in a small bowl to make the sauce.",
      "Heat oil in a large wok or skillet over high heat.",
      "Add shrimp and tofu, stir-fry until shrimp is pink, about 2-3 minutes.",
      "Push ingredients to one side, add eggs and scramble.",
      "Add drained noodles and sauce, toss everything together for 2-3 minutes.",
      "Add bean sprouts and green onions, stir-fry for another minute.",
      "Serve immediately with crushed peanuts, lime wedges, and additional fish sauce if desired.",
    ],
  },
  {
    id: "chicken-teriyaki",
    title: "Chicken Teriyaki Bowl",
    description: "Glazed chicken thighs served over steamed rice with vegetables and teriyaki sauce.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 30,
    servings: 4,
    difficulty: "Easy" as const,
    rating: 4.4,
    category: "Asian",
    ingredients: [
      "8 boneless chicken thighs",
      "1/2 cup soy sauce",
      "1/4 cup mirin",
      "2 tbsp brown sugar",
      "1 tbsp rice vinegar",
      "2 cloves garlic, minced",
      "1 tsp fresh ginger, grated",
      "2 cups cooked white rice",
      "1 cup broccoli florets",
      "1 carrot, sliced",
      "2 green onions, chopped",
      "Sesame seeds for garnish",
    ],
    instructions: [
      "Combine soy sauce, mirin, brown sugar, rice vinegar, garlic, and ginger to make teriyaki sauce.",
      "Marinate chicken thighs in half the sauce for at least 15 minutes.",
      "Heat a large skillet over medium-high heat and cook chicken until golden and cooked through, about 6-8 minutes per side.",
      "Steam broccoli and carrots until tender-crisp, about 5 minutes.",
      "Brush chicken with remaining teriyaki sauce and let it caramelize for 1-2 minutes.",
      "Slice chicken and serve over rice with steamed vegetables.",
      "Garnish with green onions and sesame seeds.",
      "Drizzle with any remaining teriyaki sauce before serving.",
    ],
  },
  {
    id: "beef-stir-fry",
    title: "Mongolian Beef Stir Fry",
    description: "Tender beef strips with onions and scallions in a savory-sweet sauce.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 20,
    servings: 4,
    difficulty: "Easy" as const,
    rating: 4.3,
    category: "Asian",
    ingredients: [
      "1 lb beef sirloin, sliced thin",
      "2 large onions, sliced",
      "4 green onions, cut into 2-inch pieces",
      "3 tbsp soy sauce",
      "2 tbsp brown sugar",
      "1 tbsp cornstarch",
      "2 tbsp vegetable oil",
      "2 cloves garlic, minced",
      "1 tsp fresh ginger, minced",
      "1/4 tsp red pepper flakes",
      "Cooked rice for serving",
    ],
    instructions: [
      "Toss sliced beef with cornstarch until evenly coated.",
      "Mix soy sauce, brown sugar, and red pepper flakes in a small bowl.",
      "Heat oil in a large wok or skillet over high heat.",
      "Add beef and stir-fry until browned, about 2-3 minutes. Remove and set aside.",
      "Add onions to the same pan and stir-fry until softened, about 3-4 minutes.",
      "Add garlic and ginger, stir-fry for 30 seconds until fragrant.",
      "Return beef to pan, add sauce and green onions, toss to combine.",
      "Serve immediately over steamed rice.",
    ],
  },

  // Dessert Recipes
  {
    id: "chocolate-chip-cookies",
    title: "Perfect Chocolate Chip Cookies",
    description: "Soft and chewy cookies with the perfect balance of crispy edges and gooey centers.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 25,
    servings: 24,
    difficulty: "Easy" as const,
    rating: 4.9,
    category: "Desserts",
    ingredients: ["flour", "butter", "brown sugar", "chocolate chips", "vanilla"],
    instructions: ["Mix dry ingredients", "Cream butter and sugar", "Combine", "Bake"],
  },
  {
    id: "tiramisu",
    title: "Classic Tiramisu",
    description: "Italian coffee-flavored dessert with layers of mascarpone and ladyfingers.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 30,
    servings: 8,
    difficulty: "Hard" as const,
    rating: 4.8,
    category: "Desserts",
    ingredients: ["mascarpone", "ladyfingers", "espresso", "cocoa powder", "eggs"],
    instructions: ["Prepare coffee", "Make mascarpone mixture", "Layer ingredients", "Chill overnight"],
  },
  {
    id: "lemon-bars",
    title: "Tangy Lemon Bars",
    description: "Buttery shortbread crust topped with bright, tangy lemon curd and powdered sugar.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 45,
    servings: 16,
    difficulty: "Medium" as const,
    rating: 4.6,
    category: "Desserts",
    ingredients: ["flour", "butter", "lemons", "eggs", "powdered sugar"],
    instructions: ["Make crust", "Prepare lemon filling", "Bake", "Cool and dust with sugar"],
  },

  // Healthy Recipes
  {
    id: "quinoa-buddha-bowl",
    title: "Rainbow Quinoa Buddha Bowl",
    description: "Nutritious bowl with quinoa, roasted vegetables, avocado, and tahini dressing.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 35,
    servings: 2,
    difficulty: "Easy" as const,
    rating: 4.5,
    category: "Healthy",
    ingredients: ["quinoa", "sweet potato", "broccoli", "avocado", "tahini"],
    instructions: ["Cook quinoa", "Roast vegetables", "Prepare dressing", "Assemble bowl"],
  },
  {
    id: "greek-salad",
    title: "Mediterranean Greek Salad",
    description: "Fresh salad with tomatoes, cucumbers, olives, feta cheese, and olive oil dressing.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 15,
    servings: 4,
    difficulty: "Easy" as const,
    rating: 4.4,
    category: "Healthy",
    ingredients: ["tomatoes", "cucumbers", "red onion", "feta cheese", "olives"],
    instructions: ["Chop vegetables", "Make dressing", "Combine ingredients", "Serve fresh"],
  },
  {
    id: "salmon-avocado-bowl",
    title: "Grilled Salmon Avocado Bowl",
    description: "Protein-packed bowl with grilled salmon, avocado, brown rice, and fresh vegetables.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 25,
    servings: 2,
    difficulty: "Medium" as const,
    rating: 4.7,
    category: "Healthy",
    ingredients: ["salmon fillet", "avocado", "brown rice", "spinach", "lemon"],
    instructions: ["Cook rice", "Grill salmon", "Prepare vegetables", "Assemble bowl"],
  },

  // Quick Meals
  {
    id: "chicken-quesadilla",
    title: "Cheesy Chicken Quesadilla",
    description: "Quick and easy quesadilla with seasoned chicken, cheese, and peppers.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 15,
    servings: 2,
    difficulty: "Easy" as const,
    rating: 4.3,
    category: "Quick Meals",
    ingredients: ["tortillas", "chicken breast", "cheese", "bell peppers", "onion"],
    instructions: ["Cook chicken", "Sauté vegetables", "Assemble quesadilla", "Cook until crispy"],
  },
  {
    id: "pasta-aglio-olio",
    title: "Spaghetti Aglio e Olio",
    description: "Simple Italian pasta with garlic, olive oil, and red pepper flakes. Ready in 15 minutes.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 15,
    servings: 4,
    difficulty: "Easy" as const,
    rating: 4.2,
    category: "Quick Meals",
    ingredients: ["spaghetti", "garlic", "olive oil", "red pepper flakes", "parsley"],
    instructions: ["Cook pasta", "Sauté garlic", "Combine with pasta", "Serve immediately"],
  },
  {
    id: "egg-fried-rice",
    title: "Quick Egg Fried Rice",
    description: "Fast and satisfying fried rice with eggs, vegetables, and soy sauce.",
    imageUrl: "/placeholder.svg?height=200&width=300",
    cookTime: 12,
    servings: 3,
    difficulty: "Easy" as const,
    rating: 4.1,
    category: "Quick Meals",
    ingredients: ["cooked rice", "eggs", "frozen vegetables", "soy sauce", "sesame oil"],
    instructions: ["Scramble eggs", "Stir-fry rice", "Add vegetables", "Season and serve"],
  },
]

// Helper function to get recipes by category
export function getRecipesByCategory(category: string) {
  return mockRecipes.filter((recipe) => recipe.category.toLowerCase() === category.toLowerCase())
}

// Helper function to get all recipes
export function getAllRecipes() {
  return mockRecipes
}

// Helper function to get recipe by ID
export function getRecipeById(id: string) {
  return mockRecipes.find((recipe) => recipe.id === id)
}
